blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="details"),
    path("<int:pk>/update/", views.UpdateView.as_view(), name="update"),
    path("create/", views.CreateView.as_view(), name="create"),
    path("<int:pk>/confirm_delete/", views.DeleteView.as_view(), name="confirm_delete"),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Post(models.Model):
    blog_title = models.CharField(max_length=50)
    blog_content = models.TextField()
    pb_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, max_length=50, on_delete=models.CASCADE)
    category = models.CharField(max_length=40)
    tag = models.CharField(max_length=40)

    def __str__(self):
        return self.blog_title

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.db import models
from django.contrib.auth.models import User
from .models import Post
from django.views import generic
from django.urls import reverse_lazy


class IndexView(generic.ListView):
    model = Post
    template_name = "blog/index.html"
    context_object_name = "latest_blog_list"

    def get_queryset(self):
        return Post.objects.order_by("-pb_date")[:5]


class DetailView(generic.DetailView):
    model = Post
    template_name = "blog/details.html"
    context_object_name = "blog"


class CreateView(generic.CreateView):
    model = Post
    template_name = "blog/post_form.html"
    fields = ["blog_title", "blog_content", "author", "category", "tag"]
    success_url = reverse_lazy("blog:index")


class UpdateView(generic.UpdateView):
    model = Post
    template_name = "blog/post_form.html"
    context_object_name = "blog"
    fields = ["blog_title", "blog_content", "author", "category", "tag"]
    success_url = reverse_lazy("blog:index")


class DeleteView(generic.DeleteView):
    model = Post
    template_name = "blog/confirm_delete.html"
    context_object_name = "blog"
    success_url = reverse_lazy("blog:index")

blog/templates/blog/confirm_delete.html
<h1>Confirm Delete</h1>
<p>Are you sure , you want to delete it?</p>

<form action="{% url 'blog:confirm_delete' pk=blog.pk %}" method="post">
  {% csrf_token %}
  <button type="submit">Yes Delete</button>
</form>
<a href="{% url 'blog:details' pk=blog.pk %}">Back</a>

blog/templates/blog/details.html
<h1>{{blog.blog_title}}</h1>
<p>{{blog.pb_date}}</p>
<p>{{blog.blog_content}}</p>
<p>~{{blog.author}}</p>
<p>{{blog.category}}</p>
<p>{{blog.tag}}</p>

<a href="{% url 'blog:update' pk=blog.pk %}">edit</a>
<a href="{% url 'blog:confirm_delete' pk=blog.pk %}">Delete blog</a>
<a href="{% url 'blog:index' %}">Back</a>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blog</title>
  </head>
  <body>
    <h1>Latest Blog Posts</h1>
    <ul>
      {% for blog in latest_blog_list %}
      <li>
        <a href="{% url 'blog:details' pk=blog.pk %}"
          ><h2>{{blog.blog_title}}</h2></a
        >
      </li>
      {% endfor %}
    </ul>
    <a href="{% url 'blog:create' %}">Create New BLog</a>
  </body>
</html>

blog/templates/blog/post_form.html
{% if blog.pk %}

<h1>Edit Blog</h1>
<form action="{% url 'blog:update' pk=blog.pk %}" method="post">
  {% csrf_token %} {{form.as_p}}
  <button type="submit">Post</button>
</form>
<a href="{% url 'blog:details' pk=blog.pk %}">Back</a>
<a href="{% url 'blog:confirm_delete' pk=blog.pk %}">Delete blog</a>
{% else %}

<h1>Create Blog</h1>
<form action="{% url 'blog:create' %}" method="post">
  {% csrf_token %} {{form.as_p}}
  <button type="submit">Post</button>
</form>
<a href="{% url 'blog:index' %}">Back</a>

{% endif %}